### ISSUE TITLE
No package error

### ISSUE THREAD

**Issue by rankinstudio** [sebo-b/TicFocuser-ng#2]
When running: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..

Error: 'No package 'libpololu-tic-1' found

I successfully installed the pololu software and launched the config - controlled the motor.

Any ideas?

Raspberry pi4 running Astroberry.

Thanks

**Comment by rankinstudio** [comment]
Figured it out, needed to compile libpololu.

**Comment by sebo-b** [comment]
Hi,

good that you figured it out. However, feel free to checkout v1.0-rc it should work better and has better library detection.

**Comment by Leforgeron-42** [comment]
Hello
I'm not a computer person and I'm a bit messy. I had installed tic focuser ng on raspberry pi 64 with stellarmate.
I was very happy with how it worked. Then I had a power outage at night which forced me to reinstall everything on my pi 4. I can no longer reinstall tic Focuser-Ng because after having built the Build I have a message of error telling me that in line 7 of CMakeLists.txt no CXX compiler found.
Can you help me ?
Thanks . Sorry for my English.
