### ISSUE TITLE
No tic device found

### ISSUE THREAD

**Issue by nati** [sebo-b/TicFocuser-ng#6]
Thank you for a great project! I've built one for me and I can control it from the latest tiggui.
However, I got "No tic device found" error on Ekos indi option tab.

I've specified the serial number of my moter but I got no luck.
I've tried libpololu but TicFocuser starts crashing on starting indi connection with it.

OS: Astroberry
RaspberryPi 4b

**Comment by nati** [comment]
I found a root cause. My tic board is T500 and If I update this line to include T500 all functions works fine :)
https://github.com/sebo-b/TicFocuser-ng/blob/master/connection/ticlib/TicUsb.cpp#L85

**Comment by sebo-b** [comment]
HI,

great that you have found the root cause - it will be hard to find it "remotely". However, it shows that tic-library should be updated to support all new TICs, but to do that I would need to re-test it - anyway, I will try to do it someday.

Keeping this issue open, so it reminds me to do the update.

**Comment by sebo-b** [comment]
Ahh.. actually it is clearly a copy&paste bug, different models should be listed there. Anyway - something to be fixed.

**Comment by sebo-b** [comment]
It is fixed (together with libtic update) in commit 629ea51453fc2d498c9c320361baee0b17453c0c.

I currently don't have access to a physical focuser, so I would appreciate if you can check if it works correctly.

**Comment by nati** [comment]
Awesome. Thanks! New version works fine with my T500 :)
